/**
 * Type describing the JSON declaration of a Protobuf service method generated by pbjs.
 */
export type MethodJson = {
  requestType: string;
  requestStream?: boolean;
  responseType: string;
  responseStream?: boolean;
};

/**
 * Type describing the JSON declaration of a Protobuf service generated by pbjs.
 */
export type ServiceJson = {
  methods: Record<string, MethodJson>;
};

/**
 * Type that can be used to assert that subtype of {@link $protobuf.rpc.Service} also matches
 * the associated service declaration in JSON format generated by pbjs.
 */
export type ServiceTypeGuard<GeneratedServiceJson extends ServiceJson> = {
  prototype: {
    [K in Uncapitalize<keyof GeneratedServiceJson['methods'] & string>]: (...args: never[]) => void;
  }
};
